version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  reviewers:
  - squeedee
  - mamachanko
- package-ecosystem: gomod
  directory: "/"
  groups:
    kubernetes:
      patterns:
      - "k8s.io/*"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  reviewers:
  - squeedee
  - mamachanko
- package-ecosystem: gomod
  directory: "/hack"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  reviewers:
  - squeedee
  - mamachanko
